### ISSUE TITLE
BitsAndBytes Quantization in LLaMA-2: Impact on Performance and Resources

### ISSUE THREAD

**Issue by rbqlsquf** [Mongjin/llama2_Instruct_Tuning#5]
How does the code utilize BitsAndBytes quantization configurations in the LLaMA-2 model, and what impact does this have on the model's performance and resource utilization during text generation tasks?

**Comment by Mongjin** [comment]
Please see our code for configurations. I am not sure about the impact of our quantization since we did not experiment for full fine-tuning.
